name: Test workflows

env:
  DEPLOY: ${{ contains(join(github.event.commits.*.message, ' '), '#deploy') }}

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  print_commit_message:
    runs-on: ubuntu-22.04
    steps:
      - name: Print commit message
        run: echo ${{ github.env.DEPLOY }}
  if_statement:
    if: github.env.DEPLOY == 'true'
    runs-on: ubuntu-22.04
    steps:
      - name: Print commit message
        run: echo "The flag is true"
