name: Test new workflows

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  print_commit_message:
    runs-on: ubuntu-22.04
    steps:
      - name: Print commit message
        run: echo ${{ contains(join(github.event.commits.*.message, ' '), '#deploy') }}
  if_statement:
    if: ${{ contains(join(github.event.commits.*.message, ' '), '#deploy') }}
    runs-on: ubuntu-22.04
    steps:
      - name: Print commit message
        run: echo "The flag is true"
